'use strict';

const fs = require('fs');
const path = require('path');
require('dotenv').config();

const { stripEnvQuotes, parseEnvBoolean, parseCsv, parseInteger } = require('./env-utils');

const ROOT_DIR = path.join(__dirname, '..', '..');
const LEGACY_CONFIG_PATH = path.join(ROOT_DIR, 'config.json');

const ADMIN_LANGUAGE_OPTIONS = new Set(['es', 'en', 'pt', 'fr', 'de', 'it']);
const UI_LANGUAGE_OPTIONS = new Set(['es', 'en', 'pt', 'fr', 'de']);
const COOKIE_SAME_SITE_OPTIONS = new Set(['lax', 'strict', 'none']);

// Compatibility bridge for older installs that still have config.json. New
// deployments should use environment variables generated by setup.js.
function readLegacyConfig(logger = console) {
  if ((process.env.TELEGRAM_TOKEN && process.env.TELEGRAM_ADMIN_ID) || !fs.existsSync(LEGACY_CONFIG_PATH)) {
    return null;
  }

  try {
    const legacyConfig = JSON.parse(fs.readFileSync(LEGACY_CONFIG_PATH, 'utf8'));
    logger.warn?.('Usando config.json legado. Migra a .env con: node setup.js');
    return legacyConfig;
  } catch (error) {
    logger.warn?.({ err: error }, 'No se pudo leer config.json');
    return null;
  }
}

// Admin language controls the operator-facing translations for visitor messages.
function normalizeAdminLanguage(lang) {
  const baseLang = typeof lang === 'string' ? lang.toLowerCase().split('-')[0] : '';
  return ADMIN_LANGUAGE_OPTIONS.has(baseLang) ? baseLang : 'es';
}

// UI language is intentionally narrower because only the bundled demo/admin
// screens have complete copy for these locales.
function normalizeUiLanguage(lang) {
  const baseLang = typeof lang === 'string' ? lang.toLowerCase().split('-')[0] : '';
  return UI_LANGUAGE_OPTIONS.has(baseLang) ? baseLang : 'es';
}

// Accept-Language can contain weighted locale lists; the first locale is enough
// for choosing static UI copy.
function languageFromHeader(header = '') {
  const candidates = String(header)
    .split(',')
    .map(part => part.trim().split(';')[0])
    .filter(Boolean);
  return normalizeUiLanguage(candidates[0] || 'es');
}

// Centralizes all runtime configuration. Values are normalized here so the rest
// of the app can depend on typed, bounded settings.
function createConfig({ logger = console } = {}) {
  const legacyConfig = readLegacyConfig(logger);
  const rawCookieSameSite = String(stripEnvQuotes(process.env.COOKIE_SAME_SITE) || 'lax').toLowerCase();
  const allowedOrigins = parseCsv(process.env.ALLOWED_ORIGINS, ['*']);

  const telegramToken = stripEnvQuotes(process.env.TELEGRAM_TOKEN || legacyConfig?.telegram?.token);
  const telegramAdminId = parseInteger(process.env.TELEGRAM_ADMIN_ID || legacyConfig?.telegram?.adminId, NaN);
  const adminLanguage = normalizeAdminLanguage(
    stripEnvQuotes(process.env.ADMIN_LANGUAGE) || legacyConfig?.admin?.language || 'es'
  );

  return {
    rootDir: ROOT_DIR,
    legacyConfig,
    telegram: {
      token: telegramToken,
      adminId: telegramAdminId,
      launchTimeoutMs: parseInteger(process.env.TELEGRAM_LAUNCH_TIMEOUT_MS || '15000', 15000),
    },
    server: {
      port: parseInteger(process.env.PORT || legacyConfig?.server?.port || '8080', 8080),
      trustProxyHops: parseInteger(process.env.TRUST_PROXY_HOPS || '1', 1),
      corsOptions: {
        origin: allowedOrigins.includes('*') ? true : allowedOrigins,
        methods: ['GET', 'POST'],
      },
    },
    widget: {
      buttonStyle: stripEnvQuotes(process.env.WIDGET_BUTTON_STYLE) || legacyConfig?.widget?.buttonStyle || 'floating',
      primaryColor: stripEnvQuotes(process.env.WIDGET_PRIMARY_COLOR) || legacyConfig?.widget?.primaryColor || '#4F46E5',
      welcomeMessage: stripEnvQuotes(process.env.WIDGET_WELCOME_MESSAGE) || legacyConfig?.widget?.welcomeMessage || '',
      apiKey: stripEnvQuotes(process.env.WIDGET_API_KEY) || '',
    },
    admin: {
      password: stripEnvQuotes(process.env.ADMIN_PANEL_PASSWORD),
      sessionTtlMs: parseInteger(process.env.ADMIN_SESSION_TTL_HOURS || '12', 12) * 60 * 60 * 1000,
      cookieName: 'lcp_admin',
      csrfCookieName: 'lcp_csrf',
      cookieSameSite: COOKIE_SAME_SITE_OPTIONS.has(rawCookieSameSite) ? rawCookieSameSite : 'lax',
      language: adminLanguage,
    },
    redis: {
      url: stripEnvQuotes(process.env.REDIS_URL) || '',
      keyPrefix: stripEnvQuotes(process.env.REDIS_KEY_PREFIX) || 'lcp',
      enabled: parseEnvBoolean(process.env.REDIS_ENABLED, process.platform !== 'win32'),
    },
    rateLimit: {
      windowMinutes: parseInteger(process.env.RATE_LIMIT_WINDOW_MINUTES || '15', 15),
      publicMax: parseInteger(process.env.RATE_LIMIT_PUBLIC_MAX || '300', 300),
      adminMax: parseInteger(process.env.RATE_LIMIT_ADMIN_MAX || '2000', 2000),
      loginMax: parseInteger(process.env.RATE_LIMIT_LOGIN_MAX || '20', 20),
      uploadWindowMinutes: parseInteger(process.env.RATE_LIMIT_UPLOAD_WINDOW_MINUTES || '1', 1),
      uploadMax: parseInteger(process.env.RATE_LIMIT_UPLOAD_MAX || '10', 10),
    },
    uploads: {
      dir: stripEnvQuotes(process.env.UPLOAD_DIR) || path.join('data', 'uploads'),
      maxMb: parseInteger(process.env.MAX_UPLOAD_MB || '5', 5),
      allowedImageTypes: parseCsv(process.env.ALLOWED_IMAGE_TYPES, ['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
    },
    features: {
      translation: parseEnvBoolean(process.env.FEATURE_TRANSLATION, legacyConfig?.features?.translation ?? true),
      sentiment: parseEnvBoolean(process.env.FEATURE_SENTIMENT, legacyConfig?.features?.sentimentAnalysis ?? true),
      ghostTyping: parseEnvBoolean(process.env.FEATURE_GHOST_TYPING, legacyConfig?.features?.ghostTyping ?? true),
      geoLocation: parseEnvBoolean(process.env.FEATURE_GEOLOCATION, legacyConfig?.features?.geoLocation ?? true),
      botNotifyAdmin: parseEnvBoolean(process.env.BOT_NOTIFY_ADMIN, false),
    },
    aiBot: {
      mode: stripEnvQuotes(process.env.BOT_MODE) || 'disabled',
      openaiKey: stripEnvQuotes(process.env.OPENAI_API_KEY),
      model: stripEnvQuotes(process.env.OPENAI_MODEL) || 'gpt-4o-mini',
      maxTokens: parseInteger(process.env.OPENAI_MAX_TOKENS, 300),
      systemPrompt:
        stripEnvQuotes(process.env.BOT_SYSTEM_PROMPT) ||
        "You are a friendly support assistant. Be brief and reply in the user's language.",
      confidenceThreshold: parseFloat(stripEnvQuotes(process.env.BOT_CONFIDENCE_THRESHOLD)) || 0.6,
      contextMessages: parseInteger(process.env.BOT_CONTEXT_MESSAGES, 6),
    },
  };
}

function validateConfig(config, { logger = console } = {}) {
  const errors = [];
  if (!config.telegram.token) {
    logger?.warn?.('TELEGRAM_TOKEN no está configurado (Telegram deshabilitado)');
  } else if (!Number.isFinite(config.telegram.adminId)) {
    errors.push('TELEGRAM_ADMIN_ID debe ser numérico');
  }
  if (!Number.isFinite(config.server.port) || config.server.port <= 0) {
    errors.push('PORT debe ser numérico y mayor que 0');
  }
  return errors;
}

module.exports = {
  createConfig,
  validateConfig,
  stripEnvQuotes,
  parseEnvBoolean,
  normalizeAdminLanguage,
  normalizeUiLanguage,
  languageFromHeader,
};
